import { useState } from 'react';
import type { Item, Meeting, Status, SyncResult } from './types';

const API='http://localhost:8080/api';
const example=`00:00:15 Ana: Pozdravljeni iz Podjetje ABC d.o.o. Želimo prenovo spletne strani.
00:01:10 Ana: Pomemben nam je obrazec za povpraševanje.
00:02:20 Ana: Potrebujemo povezavo s CRM-jem, CRM bomo še potrdili.
00:03:05 Ana: Stran mora dobro delovati tudi na telefonu.
00:04:10 Ana: Projekt bi radi zaključili do konca novembra.
00:04:35 Marko: Zaradi obsega je bolj realen december.
00:05:10 Luka: Do petka bom pripravil ponudbo.`;
async function call<T>(path:string, options?:RequestInit):Promise<T>{const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...options});if(!r.ok){const body=await r.json().catch(()=>null);throw new Error(body?.message||body?.error||`Napaka ${r.status}`)}return r.json()}
const label:Record<string,string>={agreed:'DOGOVORJENO',ai_suggestion:'AI PREDLOG',needs_review:'POTREBEN PREGLED'};
function Badge({value}:{value:string}){return <span className={`badge ${value}`}>{label[value]||value.replace('_',' ')}</span>}
function ItemEditor({item,onChange,employees}:{item:Item;onChange:(item:Item)=>void;employees:string[]}){ const change=(patch:Partial<Item>)=>onChange({...item,...patch}); return <article className={`item ${item.confidence==='low'?'attention':''}`}>
  <div className="itemtop"><Badge value={item.type}/><span className={`confidence ${item.confidence}`}>zaupanje: {item.confidence}</span></div>
  <input aria-label="Opis" value={item.description} onChange={e=>change({description:e.target.value})}/>
  <div className="fields"><label>Odgovorna oseba<select value={item.assignee||''} onChange={e=>change({assignee:e.target.value||null})}><option value="">Ni določeno</option>{employees.map(x=><option key={x}>{x}</option>)}</select></label><label>Rok<input type="date" value={item.due_date||''} onChange={e=>change({due_date:e.target.value||null})}/></label><label>Odločitev<select value={item.status} onChange={e=>change({status:e.target.value as Status})}><option value="approved">Potrjeno</option><option value="rejected">Zavrnjeno</option><option value="needs_review">Potreben pregled</option></select></label></div>
  <p className="evidence"><strong>Dokaz:</strong> „{item.source_text}“ {item.source_timestamp&&<em>({item.source_timestamp})</em>}</p>{item.reason&&<p className="reason">Zakaj predlog: {item.reason}</p>}
</article> }
export default function App(){
 const [transcript,setTranscript]=useState(''); const [meeting,setMeeting]=useState<Meeting|null>(null); const [employees,setEmployees]=useState<string[]>(['Luka','Ana','Marko']); const [clients,setClients]=useState<{name:string;contact:string}[]>([]); const [busy,setBusy]=useState(false); const [simulate,setSimulate]=useState(false); const [result,setResult]=useState<SyncResult|null>(null); const [error,setError]=useState(''); const [fallback,setFallback]=useState('');
 const analyze=async()=>{try{setBusy(true);setError('');setResult(null);const m=await call<Meeting>('/meetings/analyze',{method:'POST',body:JSON.stringify({transcript})});setMeeting(m); const [e,c]=await Promise.all([call<{name:string}[]>('/internal/employees'),call<{name:string;contact:string}[]>('/internal/clients')]);setEmployees(e.map(x=>x.name));setClients(c);}catch(e){setError(e instanceof Error?e.message:'Analiza ni uspela')}finally{setBusy(false)}};
 const updateItems=(kind:'requirements'|'action_items',updated:Item)=>setMeeting(m=>m&&({...m,[kind]:m[kind].map(i=>i.id===updated.id?updated:i)}));
 const saveReview=async()=>{if(!meeting)return;const saved=await call<Meeting>(`/meetings/${meeting.meeting_id}/review`,{method:'PUT',body:JSON.stringify({meeting})});setMeeting(saved);return saved};
 const sync=async(retry=false)=>{if(!meeting)return;try{setBusy(true);setError('');await saveReview();const r=await call<SyncResult>(`/meetings/${meeting.meeting_id}/${retry?'retry':'sync'}`,{method:'POST',body:JSON.stringify({simulateUnavailable:simulate})});setResult(r);if(r.status!=='SUCCESS')setFallback(await fetch(`${API}/meetings/${meeting.meeting_id}/manual-fallback`).then(x=>x.text()));}catch(e){setError(e instanceof Error?e.message:'Sinhronizacija ni uspela')}finally{setBusy(false)}};
 const updateConflict=(index:number,status:Status)=>setMeeting(m=>m&&({...m,conflicts:m.conflicts.map((c,i)=>i===index?{...c,status}:c)}));
 return <main><header><div><p className="eyebrow">AI MEETING ASSISTANT</p><h1>Od transkripta do sigurnog sljedećeg koraka</h1><p>AI pripravi predlog. Zaposleni potrdi poslovno pomembne podatke pred sinhronizacijo.</p></div><span className="shield">Človeška kontrola</span></header>
 <section className="card step"><h2><span>1</span> Vnos transkripta</h2><p>AI pripravi strukturiran predlog. Pred potrditvijo se v poslovni sistem ne zapiše nič.</p><textarea value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder="Prilepite transkript sestanka ..."/><div className="actions"><button className="secondary" onClick={()=>setTranscript(example)}>Naloži primer transkripta</button><button disabled={!transcript.trim()||busy} onClick={analyze}>{busy?'Analiziram ...':'Analiziraj transkript'}</button></div></section>
 {error&&<div className="alert error">{error}</div>}
 {meeting&&<><section className="card step"><h2><span>2</span> Pregled AI-rezultata <Badge value={meeting.overall_confidence}/></h2><div className="grid"><div><h3>Podatki o stranki</h3><label>Izbrani klient<select value={meeting.client.name||''} onChange={e=>{const c=clients.find(x=>x.name===e.target.value);setMeeting({...meeting,client:{name:e.target.value||null,contact_person:c?.contact||null}})}}><option value="">Ročno izberite klienta</option>{clients.map(c=><option key={c.name} value={c.name}>{c.name}</option>)}</select></label><p>{meeting.client.contact_person||'Kontakt ni določen'}</p></div><div><h3>Povzetek sestanka</h3><textarea className="summary" value={meeting.meeting_summary} onChange={e=>setMeeting({...meeting,meeting_summary:e.target.value})}/></div></div>
 <h3>Zahteve stranke</h3>{meeting.requirements.map(i=><ItemEditor key={i.id} item={i} employees={employees} onChange={x=>updateItems('requirements',x)}/>)}
 <h3>Dogovorjene naloge in AI-predlogi</h3>{meeting.action_items.map(i=><ItemEditor key={i.id} item={i} employees={employees} onChange={x=>updateItems('action_items',x)}/>)}
 <h3>Odprta vprašanja</h3>{meeting.open_questions.map(q=><blockquote key={q.question}>“{q.question}” <small>Dokaz: {q.source_text}; zaupanje: {q.confidence}</small></blockquote>)}
 <h3>Konflikti, ki zahtevajo odločitev</h3>{meeting.conflicts.map((c,i)=><div className="conflict" key={c.field}><strong>{c.field}:</strong> „{c.first_value}“ ↔ „{c.second_value}“ <Badge value={c.status}/><select value={c.status} onChange={e=>updateConflict(i,e.target.value as Status)}><option value="needs_review">Potreben pregled</option><option value="approved">Potrjeno / popravljeno</option><option value="rejected">Zavrnjeno</option></select></div>)}
 <h3>Osnutek follow-up e-maila</h3><textarea className="email" readOnly value={meeting.follow_up_email}/></section>
 <section className="card step"><h2><span>3</span> Potrditev in sinhronizacija</h2><label className="check"><input type="checkbox" checked={simulate} onChange={e=>setSimulate(e.target.checked)}/> Simuliraj nedosegljiv interni API</label><p>V sinhronizacijo se pošljejo le potrjene postavke. AI-predlog se nikoli ne spremeni v nalogo brez vaše potrditve.</p><div className="actions"><button onClick={()=>sync(false)} disabled={busy}>Potrdi in sinhroniziraj</button>{result&&result.status!=='SUCCESS'&&<button className="secondary" onClick={()=>sync(true)} disabled={busy}>Poskusi ponovno</button>}</div>{result&&<div className={`alert ${result.status==='SUCCESS'?'success':'warning'}`}><strong>{result.status}</strong> — {result.message}{result.meetingNoteId&&<div>Ustvarjen zapisnik: {result.meetingNoteId}; naloge: {result.taskIds.join(', ')||'brez novih nalog'}</div>}</div>}{fallback&&<div className="fallback"><h3>Ročni fallback</h3><p>Podatki so varno shranjeni. Kopirajte potrjene podatke za nujno ročno obravnavo.</p><textarea readOnly value={fallback}/></div>}</section></>}
 </main>;
}
